FROM python:3.13.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /code
ENV PATH="/code/.venv/bin:$PATH"

# Install PostgreSQL client library
# the slim image does not include the necessary libraries like libpq for PostgreSQL
RUN apt-get update && apt-get install -y libpq5 && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml .python-version uv.lock ./
RUN uv sync --locked

COPY taxi_data_ingestion/NYC_TAXI_DATA_V1.py .

ENTRYPOINT ["uv", "run", "python", "NYC_TAXI_DATA_V1.py"]